/* ============================================================
   THE WILD ROBOT — BOOK CLUB APP DATA
   Content data only. No markup/behaviour lives in this file.
   ============================================================ */

const RUBRIC = [
  { code: "R1", label: "LRV Ideas", desc: "Understands ideas within, across, and beyond the text." },
  { code: "R2", label: "LRV Structure & Language", desc: "Understands how the text is shaped for its audience." },
  { code: "R3", label: "LRV Processes & Strategies", desc: "Integrates strategies to form and express ideas." },
  { code: "R4", label: "SWP Ideas", desc: "Selects, forms and communicates ideas." },
  { code: "R5", label: "SWP Structure & Language", desc: "Uses language features appropriately." },
  { code: "R6", label: "SWP Processes & Strategies", desc: "Uses processes/strategies to communicate confidently." },
  { code: "R7", label: "Relating to Others", desc: "Key Competency — works well with others." },
  { code: "R8", label: "Thinking", desc: "Key Competency — thinks critically and creatively." },
  { code: "R9", label: "Participating & Contributing", desc: "Key Competency — takes part and contributes." },
  { code: "R10", label: "Core Value: Kindness, Adaptability & Belonging", desc: "Connects with the book's central value." },
];

const RUBRIC_LEVELS = ["Not Achieved", "Working Towards", "Achieved"];
const RUBRIC_LEVEL_SHORT = ["NA", "WT", "A"];

/* ------------------------------------------------------------
   MARKING GUIDE — 3 levels, pitched at NZC Level 3 (Years 5–6).
   "Achieved" = the curriculum expectation has been met.
   curriculum: the achievement objective / competency being assessed
   expect:     what the student should be able to do (teacher language)
   kid:        the same thing as a student "I can" statement
   ask:        one quick question the teacher can ask themselves when marking
   na/wt/ach:  level descriptors
   exemplar:   what an Achieved response looks like (student sample)
   wtSample:   a Working Towards response, for contrast
   evidence:   where in the unit to find the evidence
   ------------------------------------------------------------ */
const MARKING_GUIDE = [
  { code: "R1", label: "Ideas", strand: "Listening, Reading & Viewing",
    curriculum: "Show a developing understanding of ideas within, across, and beyond texts.",
    expect: "Explains the big ideas of the story (belonging, kindness, adapting) and supports them with events from the book, making links beyond the text to self or the world.",
    kid: "I can explain a big idea from the story and back it up with something that happened in the book.",
    ask: "Does the student explain WHY an event matters — not just WHAT happened?",
    na: "Retells some events but cannot yet explain what they mean. Answers are mostly 'what happened'.",
    wt: "Names a big idea (e.g. 'it's about friendship') with a general reason, but the link to the book is vague or missing.",
    ach: "Explains a big idea and supports it with a specific event from the book. Makes a link beyond the text (to self or the world).",
    wtSample: "The book is about friendship because Roz makes friends with the animals.",
    exemplar: "I think the biggest idea is that family is made by caring, not by being the same. Roz is a robot and Brightbill is a goose, but she feeds him, teaches him and protects him, so he calls her Mama. It's like my cousin who was adopted — she's just as much part of our family.",
    evidence: "Comprehension & inference answers, Friday quizzes, go-away reflections" },

  { code: "R2", label: "Structure & Language", strand: "Listening, Reading & Viewing",
    curriculum: "Show a developing understanding of how texts are shaped for different purposes and audiences, and how language features are used for effect.",
    expect: "Notices the choices the author makes — short chapters, Roz's logical robot voice, the changing seasons and setting, the illustrations — and explains how they affect the reader.",
    kid: "I can notice how the author wrote the book and explain how it makes the reader think or feel.",
    ask: "Does the student name a writer's choice AND say what effect it has on the reader?",
    na: "Comments only on the plot; does not yet notice how the book is written.",
    wt: "Notices a feature (e.g. 'the chapters are short') but cannot explain its effect.",
    ach: "Names a writer's choice and explains its effect on the reader, using an example from the book.",
    wtSample: "The chapters are really short and there are pictures.",
    exemplar: "When winter comes, the author uses lots of cold, harsh describing words and the pictures get darker. The setting gets worse as things get worse for Roz, so I felt worried before anything bad even happened. The short chapters make it feel fast, like I had to keep reading.",
    evidence: "Setting & language questions (esp. Weeks with R2), inference answers, class discussion" },

  { code: "R3", label: "Processes & Strategies", strand: "Listening, Reading & Viewing",
    curriculum: "Integrate sources of information, processes, and strategies with developing confidence to identify, form, and express ideas.",
    expect: "Uses reading strategies — predicting, questioning, making connections, summarising — and links earlier chapters to later ones (cause and effect across the book).",
    kid: "I can use reading strategies and link what happened earlier in the book to what happens later.",
    ask: "Can the student connect an earlier event to a later one without being told?",
    na: "Relies on the teacher to explain the story; does not yet connect chapters.",
    wt: "Uses a strategy when prompted (e.g. predicts when asked) and makes simple links between chapters.",
    ach: "Independently uses strategies and explains how an earlier event causes or sets up a later one.",
    wtSample: "Roz helped the animals and then they helped her.",
    exemplar: "In Week 6 Roz helped lots of animals get ready for winter. That's why in Week 7, when she nearly froze, the animals came to save her — her kindness earlier caused them to help her later. I predicted that would matter when she started helping everyone.",
    evidence: "Predictions, cause-and-effect questions, weekly quizzes (review questions)" },

  { code: "R4", label: "Ideas", strand: "Speaking, Writing & Presenting",
    curriculum: "Select, form, and communicate ideas on a range of topics.",
    expect: "Writes and shares clear, developed ideas about the book — opinions, explanations and reflections — with supporting detail.",
    kid: "I can share a clear idea or opinion and give reasons to support it.",
    ask: "Is there a clear idea PLUS at least two reasons or details?",
    na: "Answers are one word or unclear; ideas are not explained.",
    wt: "Shares a clear idea but gives little detail or only one reason.",
    ach: "Communicates a clear opinion or idea and develops it with at least two reasons or pieces of evidence.",
    wtSample: "I think Roz made the right choice because she is nice.",
    exemplar: "I think Roz made the right choice at the end. First, she was protecting the animals who had become her family. Second, she had learned that caring for others sometimes means putting them first, just like when she raised Brightbill. It was sad, but it was brave.",
    evidence: "Go-away reflections, journal projects, Week 9 opinion writing" },

  { code: "R5", label: "Structure & Language", strand: "Speaking, Writing & Presenting",
    curriculum: "Use language features appropriately, showing a developing understanding of their effects; organise texts using a range of structures.",
    expect: "Chooses the right structure and language for the task — a diary or log in Roz's voice, a persuasive poster, a comic, a script.",
    kid: "I can choose the right kind of writing and words for the job (like a diary, a poster or a log).",
    ask: "Does the writing look and sound like the form it's meant to be?",
    na: "Writing does not match the task; little attempt at structure or language features.",
    wt: "Attempts the right form (e.g. writes a diary) but the language or structure is inconsistent.",
    ach: "Uses a suitable structure and language features for the purpose and audience (e.g. a logical robot voice for Roz's log; persuasive language for a poster).",
    wtSample: "Dear diary, today I woke up on an island and it was scary and I saw some animals and they ran away.",
    exemplar: "LOG ENTRY 1. Location: unknown island. Status: fully operational. Observation: the creatures here run when I approach. Hypothesis: they are afraid of my size and my sounds. Plan: stay still, observe quietly and copy their behaviour.",
    evidence: "Poster, comic, drama & journal projects; Week 10 campaign / anthology" },

  { code: "R6", label: "Processes & Strategies", strand: "Speaking, Writing & Presenting",
    curriculum: "Integrate sources of information, processes, and strategies with developing confidence to identify, form, and express ideas.",
    expect: "Plans, drafts, revises and shares work, using feedback to improve it.",
    kid: "I can plan my work, improve it, and use feedback to make it better.",
    ask: "Can you see a plan AND a change made because of feedback?",
    na: "Needs step-by-step support to start; work is not planned or revised.",
    wt: "Plans and drafts with support; makes small changes when prompted.",
    ach: "Independently plans, drafts and revises, and uses feedback (e.g. Glow & Grow) to improve the work.",
    wtSample: "I finished my comic. My teacher told me to add colour so I did.",
    exemplar: "My plan had three parts: the beginning, the storm and the ending. My partner's 'grow' said my ending was rushed, so I added two more panels showing how Brightbill felt when he came back. Now the story makes more sense.",
    evidence: "Project plans, Week 10 planning lesson, Glow & Grow feedback" },

  { code: "R7", label: "Relating to Others", strand: "Key Competency",
    curriculum: "Relating to others: listen actively, recognise different points of view, negotiate and share ideas.",
    expect: "Listens to and builds on others' ideas during group reading and projects, and takes turns fairly.",
    kid: "I can listen to my group, take turns, and build on other people's ideas.",
    ask: "Does the student respond to what others say, not just wait for their own turn?",
    na: "Rarely listens or takes part in group reading; may interrupt or opt out.",
    wt: "Takes part and takes turns when reminded; sometimes responds to others' ideas.",
    ach: "Listens actively, takes turns, and builds on or respectfully challenges others' ideas.",
    wtSample: "(Observed) Reads their turn when the group reminds them; agrees with others but doesn't add to their ideas.",
    exemplar: "(Observed) \"I sort of disagree with Jack — I think the animals were scared, not mean, because they'd never seen a robot before.\" She then asked the quieter group members what they thought.",
    evidence: "Tuesday & Thursday group reads (turn tracker), drama projects — teacher observation" },

  { code: "R8", label: "Thinking", strand: "Key Competency",
    curriculum: "Thinking: use creative, critical and metacognitive processes to make sense of information, experiences and ideas.",
    expect: "Makes inferences — works out what characters feel and why — using clues from the text, and thinks creatively about possibilities.",
    kid: "I can use clues in the story to work out things the author doesn't tell me.",
    ask: "Has the student worked something out AND pointed to the clue?",
    na: "Only answers questions where the answer is stated directly in the text.",
    wt: "Makes an inference with prompting but struggles to explain the clue.",
    ach: "Independently infers feelings or motives and points to the clue in the text that shows it.",
    wtSample: "Roz is lonely because nobody likes her.",
    exemplar: "The book doesn't say Roz is lonely, but the animals keep running away from her and she watches them from a distance. That clue tells me she wants to belong but doesn't know how yet.",
    evidence: "Inference questions (Question 2 every day), quizzes, predictions" },

  { code: "R9", label: "Participating & Contributing", strand: "Key Competency",
    curriculum: "Participating and contributing: be actively involved in groups and communities, contributing and taking responsibility.",
    expect: "Contributes ideas in class discussions and projects, and takes responsibility for a role in group work.",
    kid: "I can share my ideas and do my part in group work.",
    ask: "Does the student offer ideas and take on a job without being asked?",
    na: "Rarely contributes to discussions or group projects.",
    wt: "Contributes when asked; completes their part of a group task with support.",
    ach: "Offers ideas without being asked, takes responsibility for a role, and encourages others.",
    wtSample: "(Observed) Shares an idea in the reflection circle when called on; completes their part of the poster.",
    exemplar: "(Observed) In the Week 10 drama group, Tane volunteered to be director, made a scene list, and made sure everyone had a part. He shared two ideas in the reflection circle without being asked.",
    evidence: "Class discussions, project work, Week 10 group project & gallery walk" },

  { code: "R10", label: "Kindness, Adaptability & Belonging", strand: "Values",
    curriculum: "Values: diversity, community and participation, respect, and care for others and the environment.",
    expect: "Connects the book's values — kindness across difference, adapting to change, belonging and found family — to their own life and actions.",
    kid: "I can connect the book's message about kindness, adapting and belonging to my own life.",
    ask: "Has the student linked a value from the book to something real in their own life?",
    na: "Cannot yet name the book's values or connect them to themselves.",
    wt: "Names a value (e.g. 'be kind') when asked, with a simple or general link.",
    ach: "Explains a value from the book and connects it to a real experience or action of their own.",
    wtSample: "The book teaches us to be kind to everyone.",
    exemplar: "Roz adapted to the island by watching and learning instead of giving up. When I moved schools I felt a bit like Roz — nobody knew me. I watched how things worked, joined in at lunch, and now I belong. One kind person made the difference, like Brightbill did for Roz.",
    evidence: "Go-away reflections, journal entries, Week 10 'How I Adapted' page, reflection circle" },
];

const CURRICULUM = {
  heading: "Curriculum Alignment — Level 3–4 English, Years 5–6, NZ Curriculum",
  lrv: [
    "Ideas: Show understanding of ideas within, across, and beyond texts.",
    "Structure and Language: Show understanding of how texts are shaped for different purposes and audiences.",
    "Processes and Strategies: Integrate sources of information, processes, and strategies confidently to identify, form, and express ideas.",
  ],
  swp: [
    "Ideas: Select, form, and communicate ideas on a range of topics.",
    "Structure and Language: Show understanding of language features, using them appropriately.",
    "Processes and Strategies: Select and use processes and strategies to communicate confidently.",
  ],
  keyCompetencies: "Relating to Others, Thinking, Managing Self, Participating & Contributing",
  values: "Kindness across difference, resilience/adaptability, belonging and found family, courage and self-sacrifice.",
  crossCurricular: "Science — Living World (adaptation, seasons, survival) and Technology (robotics/AI), since Roz must survive using the same ecological pressures that drive every wild creature on the island.",
};

// Helper to build a day object
function D(chapters, subtitle, leadIn, comp1, comp2, goAway) {
  return { chapters, subtitle, leadIn, comp1, comp2, goAway };
}
function P(type, title, brief) { return { type, title, brief }; }
function Q(q, answer, type) { return { q, answer, type: type || "short" }; }

const WEEKS = [
{
  num: 1, title: "Washed Ashore", chapters: "Chapters 1–10",
  LI: "We are learning to infer a character's feelings from their actions when the text doesn't say those feelings directly.",
  SC: "I can point to what a character does and use it to explain how they might be feeling, even when the author doesn't tell me.",
  rubricTags: ["R1","R7","R8"],
  days: {
    mon: D("Chapters 1–2", "The storm; Roz washes ashore",
      "If you woke up somewhere completely unfamiliar, with no memory of how you got there, what's the very first thing you'd try to do?",
      "What destroys the crate Roz is packed in, and how does she end up activated on the island?",
      "The chapter doesn't say Roz is \"scared\" — what details suggest she is uncertain or cautious in her first moments?",
      "Write two diary-style sentences as Roz, describing your first sight of the island."),
    tue: D("Chapters 3–5", "Roz wakes properly; first movements; watching the animals",
      "Have you ever had to learn something just by copying someone else, with no instructions? What was it?",
      "How does Roz first try to move and communicate, and what goes wrong?",
      "Why do you think the animals react with fear rather than curiosity when they see Roz?",
      "List three things Roz would need to learn to survive on the island, in order of urgency."),
    wed: D("Chapters 6–8", "First contact with island animals; being called \"the monster\"",
      "If you were the very first of your kind that anyone had ever seen, how would you want to be treated?",
      "What nickname do the island's animals give Roz, and why?",
      "What does the animals' reaction reveal about how the island community treats anything unfamiliar?",
      "Describe the island from a small animal's point of view, seeing Roz for the first time."),
    thu: D("Chapters 9–10", "Roz begins observing and mimicking animal sounds",
      "What's the hardest part of trying to fit in somewhere brand new?",
      "What method does Roz use to start understanding the animals around her?",
      "Why might learning to \"sound like\" the island's creatures matter more to Roz's survival than learning to look like them?",
      "Roz is designed to adapt to any environment. Write about one way a person you know has had to adapt to a big change."),
  },
  projects: [
    P("poster", "Have You Seen This Creature?", "Design a \"WANTED\" poster the island animals might make about Roz, based only on rumours, not facts."),
    P("comic", "Roz's First Day", "6 panels showing Roz's first day on the island from her activation to the animals fleeing from her."),
    P("drama", "The Animals' Meeting", "Act out the animals' meeting where they decide what to do about \"the monster.\""),
    P("journal", "Roz's First Log", "Write Roz's first log entry, in her own robotic, logical voice, describing what she has learned so far."),
  ],
  quiz: [
    Q("What kind of event causes Roz's crate to break open?", "A storm/shipwreck."),
    Q("True or False: Roz remembers exactly how she arrived on the island.", "False.", "tf"),
    Q("What is Roz designed to do, according to her manufacturer?", "Adapt to and survive in any environment."),
    Q("Which sense does Roz rely on most to begin learning about the island?", "Observation/sight and sound."),
    Q("What do the island animals nickname Roz?", "\"The monster\" (accept close equivalents used in your edition)."),
    Q("Why are the animals afraid of Roz at first?", "She's unfamiliar, large, and makes strange sounds/movements."),
    Q("Name one way Roz tries to communicate in her early chapters.", "Mimicking animal sounds/movements."),
    Q("Vocabulary: What does \"unfamiliar\" mean?", "Not known or recognised; strange."),
    Q("What is Roz's first major challenge on the island?", "Learning to move/function and understand her surroundings."),
    Q("True or False: The animals welcome Roz warmly straight away.", "False.", "tf"),
    Q("How does Roz's approach to learning differ from how a human child might learn?", "Open-ended — logical, observational, systematic repetition, no fear response the way an animal might have."),
    Q("What happens to the crate/packaging Roz arrived in?", "It is destroyed/lost in the storm."),
    Q("Which best describes the island: rainforest, wild uninhabited island, city park?", "Wild uninhabited island."),
    Q("Why might the author choose to have Roz \"wake up\" with no memory of arriving?", "To mirror the reader's own confusion and build sympathy for Roz as an outsider."),
    Q("What does Roz's persistence in these chapters suggest about her character?", "She is determined/logical/doesn't give up despite setbacks."),
    Q("What is one risk Roz faces simply by existing on the island?", "Being attacked/rejected by animals, or environmental damage (rocks, weather)."),
    Q("True or False: The animals immediately understand that Roz means no harm.", "False.", "tf"),
    Q("Why do you think first impressions matter so much in this story so far?", "Open-ended — they shape how Roz is treated and whether she can survive there."),
    Q("What does Roz begin practising in Chapters 9–10 to try to fit in?", "Mimicking/copying animal sounds and behaviours."),
    Q("What is one prediction you have for how Roz's relationship with the island animals might change?", "Open-ended, accept any reasonable, text-supported prediction."),
  ],
},
{
  num: 2, title: "Learning the Island's Ways", chapters: "Chapters 11–19",
  LI: "We are learning to track how a character changes over several chapters by noticing small shifts in their actions.",
  SC: "I can compare how a character behaves at the start of a section with how they behave by the end, and explain what caused the change.",
  rubricTags: ["R2","R3","R8"],
  days: {
    mon: D("Chapters 11–12", "Roz begins to understand animal language",
      "Imagine trying to learn a new language just by listening — no book, no teacher. What would be the hardest part?",
      "How does Roz's understanding of the animals' sounds begin to improve?",
      "What does it show about Roz that she keeps trying even though the animals keep avoiding her?",
      "Invent three animal \"words\" Roz might learn this week, and what they mean."),
    tue: D("Chapters 13–15", "Small, cautious interactions begin",
      "Has an animal (pet or wild) ever surprised you by trusting you when you didn't expect it to?",
      "Which animal is the first to cautiously interact with Roz, and how does that interaction go?",
      "Why might one animal be braver than the rest of the island community?",
      "Write a short conversation between Roz and the first animal that talks to her."),
    wed: D("Chapters 16–17", "Roz begins to be tolerated, still an outsider",
      "What's something that made you feel like you belonged somewhere, even a little?",
      "How does the island community's attitude toward Roz start to shift, even slightly, in these chapters?",
      "Is the island's changing opinion of Roz based on trust, or just familiarity? Explain your thinking.",
      "Describe one small act that could change how a group of people sees a newcomer."),
    thu: D("Chapters 18–19", "Roz builds early routines and begins to feel more at home",
      "What helps you feel settled in a new place — a routine, a friend, a familiar object?",
      "What routines or habits does Roz start to build for herself on the island?",
      "Why might having a routine matter just as much to a robot as it would to a person?",
      "Design a daily routine for Roz, based on what she needs to survive and what she's learned so far."),
  },
  projects: [
    P("poster", "Island Field Guide", "Create an \"Island Field Guide\" page introducing Roz to a new animal arriving on the island, from another animal's point of view."),
    P("comic", "The First to Approach", "Show the moment the first animal dares to approach Roz, panel by panel."),
    P("drama", "A Cautious First Conversation", "Act out a cautious first conversation between Roz and one of the island's animals."),
    P("journal", "Learning the Rules", "Write a log entry from Roz describing what she has learned about the island's \"rules\" so far."),
  ],
  quiz: [
    Q("How does Roz begin to understand the animals?", "By listening carefully and studying patterns in their sounds/behaviour."),
    Q("True or False: Every animal on the island quickly becomes friendly with Roz.", "False.", "tf"),
    Q("Which animal is among the first to interact more closely with Roz?", "Accept the first animal your edition introduces as curious/cautiously friendly."),
    Q("Vocabulary: What does \"cautious\" mean?", "Careful, not taking risks."),
    Q("Name one routine or habit Roz starts to build in these chapters.", "Open — e.g. observing the island each day, practising sounds."),
    Q("Why does Roz keep trying to connect with the animals despite being avoided?", "She is built to adapt/survive, and needs the island community to do so."),
    Q("True or False: Roz gives up trying to communicate after the animals avoid her.", "False.", "tf"),
    Q("What does the growing trust between Roz and the animals suggest about first impressions?", "Open-ended — first impressions can change with time and effort."),
    Q("What does Roz do to try to prove she isn't dangerous?", "Open — behaves gently, mimics friendly behaviour, avoids conflict."),
    Q("What might make an animal community slowly accept an outsider?", "Repeated safe/positive interactions, time, no threat shown."),
    Q("What is one \"rule\" of island life Roz starts to learn in these chapters?", "Open — e.g. who eats what, where danger lies, seasonal patterns."),
    Q("Vocabulary: What does \"tolerate\" mean, as opposed to \"welcome\"?", "Tolerate = allow without objecting; welcome = actively invite/embrace."),
    Q("True or False: By the end of Chapter 19, every animal fully trusts Roz.", "False — trust is only beginning.", "tf"),
    Q("How is Roz's situation similar to what a new student might feel on their first weeks at school?", "Open-ended."),
    Q("What does Roz rely on since she cannot rely on instinct the way animals do?", "Observation, logic, learning/adaptation."),
    Q("Describe one moment in these chapters where an animal shows the smallest sign of trust toward Roz.", "Open, text-based."),
    Q("Why is the island's response to Roz realistic, in your opinion?", "Open-ended — accept reasoned answers about fear of the unknown."),
    Q("What would you have done differently if you were Roz, trying to be accepted?", "Open-ended."),
    Q("True or False: Roz begins forming routines to help her survive and understand the island better.", "True.", "tf"),
    Q("Predict: What do you think might happen that finally forces the animals to see Roz differently?", "Open-ended, text-supported prediction (accept references to the coming accident)."),
  ],
},
{
  num: 3, title: "The Last Egg", chapters: "Chapters 20–28",
  LI: "We are learning to explore how an accident or mistake can change the direction of a whole story.",
  SC: "I can explain how one event causes a character to make a decision that changes everything that follows.",
  rubricTags: ["R1","R8","R10"],
  days: {
    mon: D("Chapters 20–21", "The accident — Roz stumbles into the goose nest",
      "Have you ever made a mistake that you couldn't take back, even though you didn't mean to cause harm?",
      "What happens to the goose family when Roz loses her footing on the cliffside?",
      "How do you think Roz \"feels\" (in her own robotic way) immediately after the accident, based on what she does next?",
      "Write two sentences from Roz's internal processing/log right after the accident happens."),
    tue: D("Chapters 22–23", "Guilt; discovering the one surviving egg",
      "If you accidentally broke something that mattered to someone else, what would you want to do to make it right?",
      "What does Roz find among the wreckage of the nest, and what does she decide to do about it?",
      "Why might Roz feel a sense of responsibility for the egg, even though robots aren't supposed to feel guilt?",
      "Write a short apology, in Roz's voice, to the goose family she can no longer speak to."),
    wed: D("Chapters 24–26", "Deciding to raise the egg; Fink's role",
      "Would you trust advice from someone you don't fully like or agree with? Why or why not?",
      "Who helps Roz figure out how to care for the egg, and what is that character's personality like?",
      "Why might the author choose a sly, self-interested character to be the one who helps Roz?",
      "List three things Roz will need to learn in order to keep the egg safe and help it hatch."),
    thu: D("Chapters 27–28", "The egg hatches — Brightbill imprints on Roz",
      "What do you think it means to be someone's \"family,\" if you don't look anything alike?",
      "What happens the moment the egg hatches, and how does the gosling react to Roz?",
      "Why does the gosling accept Roz as his mother, even though she is a robot?",
      "Write the first \"thought\" the newly hatched gosling might have upon seeing Roz."),
  },
  projects: [
    P("poster", "Before and After", "Design a split poster showing the nest before the accident and Roz caring for the surviving egg."),
    P("comic", "The Hatching", "Show the hatching moment and Brightbill's first sight of Roz, from Brightbill's point of view."),
    P("drama", "Roz and Fink", "Act out the conversation between Roz and Fink where he agrees to help her understand goslings."),
    P("journal", "Making It Right", "Write about a time you or someone you know took responsibility for a mistake and tried to fix it."),
  ],
  quiz: [
    Q("What causes the accident with the goose nest?", "Roz loses her balance/footing and falls, destroying the nest."),
    Q("True or False: All of the goose eggs survive the accident.", "False, only one survives.", "tf"),
    Q("What does Roz decide to do with the surviving egg?", "Keep and care for it/try to hatch it."),
    Q("Who helps guide Roz in caring for the egg?", "Fink the fox (accept the equivalent name from your edition)."),
    Q("Vocabulary: What does \"responsibility\" mean?", "Being accountable for the outcome of your actions."),
    Q("Why might Fink actually be willing to help Roz?", "Open — self-interest, curiosity, or a growing, reluctant fondness."),
    Q("True or False: Roz feels nothing at all after causing the accident.", "False — she shows guilt/responsibility through her actions.", "tf"),
    Q("What happens the moment the gosling hatches and sees Roz?", "He imprints on her, treating her as his mother."),
    Q("Why does the gosling accept a robot as his mother?", "Because imprinting is based on what a gosling sees first, not species/appearance."),
    Q("Do you think Roz caring for the egg makes up for the accident? Why or why not?", "Open-ended."),
    Q("What is one thing Roz must learn quickly in order to protect the egg?", "Open — warmth, safety from predators, patience."),
    Q("Vocabulary: What does \"imprint\" mean in this context?", "To form an early, strong attachment/bond, usually to the first moving thing seen after hatching."),
    Q("True or False: Fink is immediately kind and helpful with no hesitation.", "False — he is initially reluctant/self-interested.", "tf"),
    Q("What does this section suggest about family not needing to \"match\"?", "Open-ended."),
    Q("What does Roz name the gosling (or is he named later)?", "Accept whatever your edition establishes — \"not yet named\" is acceptable."),
    Q("Describe how Roz's role changes across this week's chapters.", "From accidental cause of harm to caretaker/mother figure."),
    Q("Why might the author want readers to feel sympathy for Roz here, right after she causes harm?", "Open-ended — shows her capacity for care/responsibility despite the accident."),
    Q("How is Fink different from the other animals we've met so far?", "Open — more cunning, self-serving, but ultimately useful/loyal."),
    Q("True or False: The gosling could have chosen to imprint on another animal instead of Roz.", "True (in theory) — but he imprinted on Roz because she was there first.", "tf"),
    Q("Predict: How do you think the other geese will react to Brightbill being raised by a robot?", "Open-ended, text-supported prediction."),
  ],
},
{
  num: 4, title: "Learning to Mother", chapters: "Chapters 29–37",
  LI: "We are learning to identify how an author shows a character learning a new skill through trial and error.",
  SC: "I can find examples in the text where a character fails, adjusts, and tries again.",
  rubricTags: ["R3","R7","R10"],
  days: {
    mon: D("Chapters 29–30", "Roz figures out feeding and basic care",
      "What's something you had to fail at a few times before you got it right?",
      "What early mistakes does Roz make while learning to care for the gosling?",
      "How does Roz's logical, methodical nature help her (or get in the way) as a new mother?",
      "Write a short \"user manual\" page Roz might write for herself titled \"How to Care for a Gosling.\""),
    tue: D("Chapters 31–33", "Other geese reject/tease Brightbill",
      "Has anyone ever teased you or someone you know for being \"different\"? How did that feel?",
      "How do the other geese react to Brightbill because of who is raising him?",
      "Why do you think the geese focus on Roz being \"different\" rather than on how well she cares for Brightbill?",
      "Write a message of support you would give Brightbill if you were his friend."),
    wed: D("Chapters 34–35", "Roz problem-solves parenting challenges with the island's help",
      "When something feels too hard to do alone, who do you ask for help?",
      "Which island animals start pitching in to help Roz raise Brightbill, and how?",
      "What does the community's willingness to help suggest about how far Roz has come since Week 1?",
      "List three ways the island community now treats Roz differently than they did in Week 1."),
    thu: D("Chapters 36–37", "The bond between Roz and Brightbill deepens",
      "What's a small moment that made you feel close to someone in your family?",
      "Describe a specific moment in these chapters that shows how close Roz and Brightbill have become.",
      "Why might small, everyday moments matter more to a growing bond than big dramatic ones?",
      "Write about a small, everyday moment that shows love or care in your own life."),
  },
  projects: [
    P("poster", "Meet the Family", "Design a \"Meet the Family\" poster introducing Roz and Brightbill as the island's most unusual family."),
    P("comic", "Roz's Early Mistakes", "Show three of Roz's early parenting mistakes and how she fixes each one."),
    P("drama", "Teasing at the Pond", "Act out the other geese teasing Brightbill, and how he responds."),
    P("journal", "What Makes a Good Parent", "Write about what you think makes someone a good parent or carer, using evidence from Roz's actions."),
  ],
  quiz: [
    Q("What is one early mistake Roz makes while learning to care for Brightbill?", "Open — e.g. wrong food, misjudging his needs."),
    Q("True or False: Roz gets everything right immediately as a new mother.", "False.", "tf"),
    Q("How do the other geese treat Brightbill because of his robot mother?", "They tease/reject/exclude him."),
    Q("Vocabulary: What does \"reject\" mean?", "To refuse to accept or include."),
    Q("Name one island animal that starts helping Roz raise Brightbill.", "Open, accept text-supported answer."),
    Q("Why might Roz's logical approach sometimes clash with what a gosling actually needs?", "Open-ended — instincts/emotions vs. pure logic."),
    Q("True or False: Roz never adjusts her methods, even when they don't work.", "False — she learns and adapts through trial and error.", "tf"),
    Q("Why do you think Brightbill stays loyal to Roz even when teased by other geese?", "Open — she is the one who cares for/loves him regardless."),
    Q("What does this section suggest about what \"family\" really means?", "Open-ended — care and bond matter more than sameness/appearance."),
    Q("Describe one small, tender moment between Roz and Brightbill from these chapters.", "Open, text-based."),
    Q("Vocabulary: What does \"bond\" mean in the context of a relationship?", "A close connection or attachment between individuals."),
    Q("True or False: The island community is completely unwilling to help Roz with Brightbill.", "False — some animals start helping.", "tf"),
    Q("How has the island's view of Roz changed since Week 1?", "Open-ended, but should reference growing trust/acceptance."),
    Q("Why might the author include the other geese's teasing rather than skip straight to acceptance?", "Open-ended — shows realistic social struggle, raises the emotional stakes."),
    Q("What does Roz do when her first attempts at caring for Brightbill fail?", "She observes, adjusts, and tries again."),
    Q("What would you say to Brightbill if you were his friend on the island?", "Open-ended."),
    Q("What quality does Roz show throughout this week that helps her succeed as a mother?", "Open — patience, persistence, adaptability, care."),
    Q("True or False: Brightbill begins to trust and rely on Roz more as the weeks go on.", "True.", "tf"),
    Q("Give one piece of evidence that Roz genuinely cares for Brightbill, beyond just \"programming.\"", "Open, text-based."),
    Q("Predict: How do you think Brightbill's relationship with the other geese might change over time?", "Open-ended, text-supported prediction."),
  ],
},
{
  num: 5, title: "Finding Her Place", chapters: "Chapters 38–46",
  LI: "We are learning to notice how setting (season, weather, environment) reflects or affects a character's mood and situation.",
  SC: "I can describe how a change in setting connects to what a character is going through at that point in the story.",
  rubricTags: ["R2","R9"],
  days: {
    mon: D("Chapters 38–39", "Summer arrives; island life in full swing",
      "What does your favourite season feel like, and why do you love it?",
      "How is island life described during summer in these chapters?",
      "Why might summer be a natural \"high point\" for Roz and Brightbill's story so far?",
      "Describe a summer memory of your own that made you feel happy or free."),
    tue: D("Chapters 40–42", "Roz helps solve problems for other animals",
      "What's a skill or strength of yours that helps other people?",
      "What problem(s) does Roz help solve for other island animals in these chapters?",
      "How does helping others change how the island community sees Roz?",
      "Invent one more problem Roz could help an island animal solve, and explain how she'd do it."),
    wed: D("Chapters 43–44", "Roz teaches Brightbill to swim/forage",
      "What's something an adult in your life taught you how to do?",
      "What survival skills does Roz teach Brightbill in these chapters?",
      "Why is it important that Roz teaches Brightbill skills a goose actually needs, even though she isn't a goose?",
      "Write step-by-step instructions Roz might give Brightbill for one of these skills."),
    thu: D("Chapters 45–46", "Brightbill's first, clumsy attempts at flight",
      "Describe a time you tried something new and it didn't go smoothly at first.",
      "What happens when Brightbill first tries to fly?",
      "How does Roz react to Brightbill's failed attempts, and what does that reveal about her as a parent?",
      "Write an encouraging note from Roz to Brightbill after his first failed flying attempt."),
  },
  projects: [
    P("poster", "Roz's Island Services", "Create a poster listing the ways Roz now helps the island community."),
    P("comic", "First Flight Fail", "Show Brightbill's first flying attempt going wrong, panel by panel, ending on a hopeful note."),
    P("drama", "Teaching a Skill", "Act out Roz teaching Brightbill a survival skill, in role as teacher and student."),
    P("journal", "Encouraged After Failing", "Write about a time someone encouraged you after you failed at something the first time."),
  ],
  quiz: [
    Q("What season is it during these chapters?", "Summer."),
    Q("True or False: Roz has become fully rejected by the island community by this point.", "False — she is now helping and becoming accepted.", "tf"),
    Q("Name one problem Roz helps an island animal solve.", "Open, text-based."),
    Q("Vocabulary: What does \"forage\" mean?", "To search for and find food."),
    Q("What survival skill(s) does Roz teach Brightbill in these chapters?", "Open — swimming, foraging, etc."),
    Q("Why is it notable that Roz, a robot, can teach a goose to do goose things?", "She learned these skills herself through observation/adaptation."),
    Q("True or False: Brightbill flies perfectly on his very first attempt.", "False.", "tf"),
    Q("How does Roz respond when Brightbill's flying attempt fails?", "Open — supportive, encouraging, patient."),
    Q("Why might summer be shown as a peaceful, happy time in the story?", "Open-ended — contrast with hardships before/after; reflects growing stability."),
    Q("Give one piece of evidence that the island community now values Roz's presence.", "Open, text-based."),
    Q("Vocabulary: What does \"community\" mean in the context of this story?", "A group of individuals living/working together and supporting one another."),
    Q("True or False: Roz only cares for Brightbill and ignores every other animal on the island.", "False — she helps other animals too.", "tf"),
    Q("What does Roz's willingness to help others suggest about her character?", "Open-ended — generous, community-minded, adaptable."),
    Q("Why might the author include Brightbill's flying failure rather than skipping to success?", "Open-ended — realistic struggle, builds emotional stakes for later success."),
    Q("Describe one specific way Roz helps Brightbill learn a new skill.", "Open, text-based."),
    Q("How has Roz's role on the island expanded since Week 1?", "Open-ended — from feared outsider to helpful, trusted member."),
    Q("What is one quality Roz shows while teaching Brightbill?", "Open — patience, encouragement, persistence."),
    Q("True or False: The island community remains just as fearful of Roz as they were in Week 1.", "False.", "tf"),
    Q("What might Brightbill need most from Roz as he keeps trying to fly?", "Open — encouragement, patience, practice opportunities."),
    Q("Predict: What challenges do you think might arrive as the seasons start to change?", "Open-ended, text-supported prediction (accept references to autumn/winter coming)."),
  ],
},
{
  num: 6, title: "Getting Ready", chapters: "Chapters 47–55",
  LI: "We are learning to identify cause and effect across a sequence of chapters, not just within a single page.",
  SC: "I can explain how an earlier event in the story causes or sets up something that happens later.",
  rubricTags: ["R3","R7","R9"],
  days: {
    mon: D("Chapters 47–48", "Autumn arrives; signs of the changing season",
      "What signs tell you that a season is about to change, even before it officially does?",
      "What signs of autumn appear on the island in these chapters?",
      "How does the mood of the story shift as autumn approaches, compared to the summer chapters?",
      "Write a short descriptive paragraph capturing the feeling of autumn arriving on the island."),
    tue: D("Chapters 49–51", "Roz organises the island for winter",
      "What's something you're good at organising or planning?",
      "What does Roz start organising to help the island prepare for winter?",
      "Why might Roz's robotic efficiency actually be a huge advantage for the island community right now?",
      "Design a simple \"winter preparation checklist\" Roz might create for the island animals."),
    wed: D("Chapters 52–53", "Community bonds strengthen through shared work",
      "Has working on a task together with others ever made you feel closer to them?",
      "How do the island animals work alongside Roz to prepare for winter?",
      "What does this shared effort suggest about how far the community has come in accepting Roz?",
      "Write about a time working together with others helped you get through something difficult."),
    thu: D("Chapters 54–55", "Worry grows about Brightbill's flying and migration",
      "What's something you've worried about before it even happened?",
      "What specific worry grows in these chapters about Brightbill?",
      "Why might Roz feel especially anxious about Brightbill's flying, given everything we know about their bond?",
      "Write Roz's private thoughts (a log entry) about her worries for Brightbill's future."),
  },
  projects: [
    P("poster", "Winter Is Coming", "Design an island preparation plan poster showing what needs to be done and by whom."),
    P("comic", "Working Together", "Show the island animals and Roz working together to prepare for winter."),
    P("drama", "The Planning Meeting", "Act out a planning meeting where Roz organises the island's winter preparations."),
    P("journal", "A Worry and a Step", "Write about something you are worried about right now, and one small step you could take about it."),
  ],
  quiz: [
    Q("What season begins in these chapters?", "Autumn."),
    Q("True or False: The island shows no signs of the season changing.", "False.", "tf"),
    Q("What does Roz begin organising to help the island?", "Shelters and food storage for winter."),
    Q("Vocabulary: What does \"efficient\" mean?", "Achieving results with minimal wasted time/effort."),
    Q("Name one way the island animals help Roz with the preparations.", "Open, text-based."),
    Q("Why might Roz's robotic nature be especially useful during this preparation period?", "Open — logical planning, tireless effort, organisation skills."),
    Q("True or False: The island community refuses to work alongside Roz.", "False — they work together.", "tf"),
    Q("What does the community's teamwork suggest about their relationship with Roz now, compared to Week 1?", "Open-ended — much stronger trust/acceptance."),
    Q("What worry grows during these chapters regarding Brightbill?", "Whether he will be ready to fly/migrate in time."),
    Q("Why might Roz feel more worried about Brightbill than about herself?", "Open-ended — love/parental care for him."),
    Q("Describe one specific task the island completes to prepare for winter.", "Open, text-based."),
    Q("Vocabulary: What does \"migration\" mean?", "The seasonal movement of animals from one region to another."),
    Q("True or False: Roz shows no concern at all about the coming winter.", "False.", "tf"),
    Q("How does the mood of the story change as autumn arrives?", "Open-ended — more urgent, tense, or reflective."),
    Q("Why might the author use \"getting ready\" chapters to build tension before winter hits?", "Open-ended — builds suspense, raises stakes for the reader."),
    Q("What is one piece of evidence that the island community now sees Roz as one of their own?", "Open, text-based."),
    Q("What does teamwork accomplish in this section that individual effort couldn't?", "Open-ended."),
    Q("True or False: Brightbill is already a confident, fully capable flyer by the end of this week.", "False — his flying is still a concern.", "tf"),
    Q("What is one way you personally prepare for a big change or challenge?", "Open-ended."),
    Q("Predict: What do you think will happen when winter actually arrives?", "Open-ended, text-supported prediction."),
  ],
},
{
  num: 7, title: "The Winter That Almost Ends Everything", chapters: "Chapters 56–64",
  LI: "We are learning to explore how a crisis moment reveals what characters truly value.",
  SC: "I can identify a moment of crisis in the text and explain what it shows about a character's values or relationships.",
  rubricTags: ["R1","R7","R10"],
  days: {
    mon: D("Chapters 56–57", "The harsh winter storm hits",
      "Describe the worst weather you've ever experienced. How did it feel?",
      "What happens when the harsh winter storm hits the island?",
      "Why might winter be an especially dangerous season for a robot like Roz, specifically?",
      "Write a short weather report describing the storm, as if you were reporting live from the island."),
    tue: D("Chapters 58–60", "Crisis — Roz nearly shuts down/freezes",
      "Has there ever been a moment where you (or someone you know) really needed help from others?",
      "What happens to Roz during the worst of the storm?",
      "Why is this moment such a turning point in Roz's relationship with the island?",
      "Write about a moment when you needed someone else's help, and how it felt to receive it."),
    wed: D("Chapters 61–62", "Animals rally to save Roz",
      "Do you believe kindness usually gets \"paid back\" eventually? Why or why not?",
      "How do the island animals respond when Roz is in danger?",
      "Why do you think the animals choose to help Roz now, after everything that's happened between them?",
      "Write a thank-you message from Roz to the animals who helped save her."),
    thu: D("Chapters 63–64", "Roz recovers; the bond is stronger than ever",
      "What does it mean to truly belong somewhere?",
      "How does Roz's relationship with the island community look different after the storm, compared to before it?",
      "What has this crisis proven about Roz's place on the island?",
      "Write about a moment that made you feel like you truly belonged somewhere."),
  },
  projects: [
    P("poster", "Breaking News", "Design a news poster reporting on the storm and the island's rescue of Roz."),
    P("comic", "The Rescue", "Show the moment the animals rally together to save Roz during the storm."),
    P("drama", "All Hands on Deck", "Act out the island's rescue effort, with different animals taking on different jobs."),
    P("journal", "Kindness Comes Back Around", "Write about the theme \"kindness comes back around,\" using evidence from this week's reading."),
  ],
  quiz: [
    Q("What event hits the island in these chapters?", "A harsh winter storm."),
    Q("True or False: Roz is completely unaffected by the winter storm.", "False — she is put in serious danger.", "tf"),
    Q("Why is winter especially dangerous for Roz specifically?", "Open — cold/ice/snow can damage or shut down her systems."),
    Q("Vocabulary: What does \"crisis\" mean?", "A time of intense danger or difficulty."),
    Q("What happens to Roz during the worst part of the storm?", "She is at risk of shutting down/freezing/being damaged."),
    Q("Who helps Roz during this crisis?", "The island animals/community."),
    Q("True or False: The animals abandon Roz during the storm.", "False — they rally to help her.", "tf"),
    Q("Why do the animals choose to help Roz now, given their history with her?", "Open — she has earned their trust and helped them before; they care about her now."),
    Q("What does this rescue reveal about how the island's feelings toward Roz have changed?", "Open-ended — from fear to genuine care/loyalty."),
    Q("Give one piece of evidence that Roz has become a true member of the island community.", "Open, text-based."),
    Q("Vocabulary: What does \"loyalty\" mean?", "Being faithful/devoted to someone or something."),
    Q("True or False: This shows that kindness Roz gave earlier in the book is now being returned.", "True.", "tf"),
    Q("How would the story be different if the animals had chosen not to help Roz?", "Open-ended."),
    Q("Why might the author place this crisis right after the \"getting ready\" chapters?", "Open-ended — raises stakes after all that preparation; tests the community's bond."),
    Q("Describe how Roz recovers after the storm.", "Open, text-based."),
    Q("What does \"found family\" mean, and how does this section show it?", "Open-ended."),
    Q("What emotion do you think Roz might \"feel\" (in her own way) after being saved?", "Open — gratitude, belonging, relief."),
    Q("True or False: After the storm, Roz's place on the island is more secure than ever.", "True.", "tf"),
    Q("Name one animal that plays a key role in helping Roz during the crisis.", "Open, text-based."),
    Q("Predict: How might this experience change Roz and Brightbill's relationship going forward?", "Open-ended, text-supported prediction."),
  ],
},
{
  num: 8, title: "Learning to Let Go", chapters: "Chapters 65–71",
  LI: "We are learning to explore how a character can feel two opposite emotions (pride and sadness) about the same event.",
  SC: "I can explain how a character might feel two conflicting emotions at once, using evidence from the text.",
  rubricTags: ["R1","R4","R8"],
  days: {
    mon: D("Chapters 65–66", "Spring thaw; renewed hope",
      "What does a \"fresh start\" feel like to you?",
      "What changes on the island as spring arrives?",
      "Why might spring be a fitting season for Brightbill to finally succeed at flying?",
      "Write about a \"fresh start\" moment in your own life."),
    tue: D("Chapters 67–68", "Brightbill finally learns to fly properly",
      "Describe a moment you finally succeeded at something after failing many times.",
      "How does Brightbill finally manage to fly successfully?",
      "What role does Roz play in this success, even though she can't fly herself?",
      "Write about Roz's mixed feelings watching Brightbill fly for the first time."),
    wed: D("Chapter 69", "The wild geese return and invite Brightbill to join them",
      "Have you ever been invited to join a group, but felt torn about whether to go?",
      "What do the wild geese offer Brightbill in this chapter?",
      "Why might this invitation be both exciting and painful for Brightbill?",
      "Write Brightbill's private thoughts as he considers the geese's invitation."),
    thu: D("Chapters 70–71", "Bittersweet preparation to say goodbye",
      "What is the hardest goodbye you've ever had to say?",
      "How do Roz and Brightbill prepare for the possibility of him leaving?",
      "Why might Roz encourage Brightbill to go, even though it means losing him?",
      "Write a letter from Roz to Brightbill, to be read after he leaves."),
  },
  projects: [
    P("poster", "Brightbill Learns to Fly", "Design a celebration poster capturing Brightbill's big moment."),
    P("comic", "First Successful Flight", "Show Brightbill's successful first flight, from struggle to success."),
    P("drama", "The Invitation", "Act out the wild geese inviting Brightbill to migrate with them, and his reaction."),
    P("journal", "Letting Someone Go", "Write about a time you had to let someone you love take a big step away from you (or imagine how that might feel)."),
  ],
  quiz: [
    Q("What season begins in these chapters?", "Spring."),
    Q("True or False: Brightbill never successfully learns to fly.", "False — he finally succeeds.", "tf"),
    Q("Who helps Brightbill achieve his successful flight?", "Roz, and/or the wild geese."),
    Q("Vocabulary: What does \"bittersweet\" mean?", "Something that is both pleasant and painful/sad at the same time."),
    Q("What do the wild geese offer Brightbill in these chapters?", "An invitation to migrate/join their flock."),
    Q("Why might this invitation feel painful as well as exciting for Brightbill?", "Open — means leaving Roz, his home, everything familiar."),
    Q("True or False: Roz tries to stop Brightbill from leaving.", "False — she encourages/supports him.", "tf"),
    Q("Why does Roz encourage Brightbill to go, even though it will hurt her?", "Open — she loves him and wants what's best for him; true care means letting go."),
    Q("What does Roz's choice to encourage Brightbill's departure reveal about her character?", "Open-ended — selfless love, growth, maturity."),
    Q("Describe how Roz and Brightbill prepare for the possibility of him leaving.", "Open, text-based."),
    Q("Vocabulary: What does \"migrate\" mean, in the context of geese?", "To travel seasonally from one region to another, often for climate/food."),
    Q("True or False: Brightbill feels only happiness about the chance to migrate, with no sadness at all.", "False — his feelings are mixed.", "tf"),
    Q("Can you feel proud and sad about the same event at the same time? Explain, using this story as an example.", "Open-ended."),
    Q("Why might the author choose spring (a season of new beginnings) for this turning point?", "Open-ended — symbolic of growth, change, moving on."),
    Q("What specific moment shows that Brightbill has finally mastered flying?", "Open, text-based."),
    Q("What does \"letting go\" mean in the context of a parent-child relationship?", "Open-ended."),
    Q("What emotions do you think Roz experiences watching Brightbill fly successfully for the first time?", "Open — pride, joy, sadness, worry."),
    Q("True or False: The wild geese's invitation comes as a complete surprise with no earlier hints.", "False — the story has been building toward migration since Week 6's worries.", "tf"),
    Q("What is one piece of advice Roz might give Brightbill before he leaves?", "Open-ended, plausible for the story."),
    Q("Predict: Do you think Brightbill will actually choose to leave with the geese? Why or why not?", "Open-ended, text-supported prediction."),
  ],
},
{
  num: 9, title: "What the Island Would Risk", chapters: "Chapters 72–80 (book finishes)",
  LI: "We are learning to evaluate how an author builds tension toward an ending, and to form our own opinion about a character's final choice.",
  SC: "I can explain how tension builds across the final chapters and give my own justified opinion about how the story ends.",
  rubricTags: ["R4","R6","R10"],
  days: {
    mon: D("Chapters 72–73", "Brightbill migrates away; Roz is alone again",
      "What do you imagine it feels like to say goodbye to someone, not knowing exactly when you'll see them again?",
      "What happens when Brightbill finally leaves with the wild geese?",
      "How is Roz's loneliness now different from her loneliness at the very start of the book?",
      "Write about how it might feel to be alone again after being part of a family for so long."),
    tue: D("Chapters 74–75", "RECOs arrive on the island",
      "If someone came looking to \"collect\" something (or someone) you cared about, what would you do?",
      "Who arrives on the island in these chapters, and what is their purpose?",
      "Why might Roz's own creators see her as something to retrieve rather than as someone with a life of her own?",
      "Write a warning message the island animals might pass to each other about the newcomers."),
    wed: D("Chapters 76–77", "The island community risks everything to protect Roz",
      "Would you take a risk to protect a friend, even if it could get you in trouble?",
      "What do the island animals do to try to protect Roz from the RECOs?",
      "What does the community's willingness to risk themselves for Roz prove about how far their relationship has come?",
      "Write about a time you (or someone you know) took a risk to help or protect someone else."),
    thu: D("Chapters 78–80", "The confrontation and Roz's ending",
      "If you had to choose between staying safe and protecting the people you love, which would you choose, and why?",
      "What ultimately happens to Roz at the end of the book?",
      "Why might Roz choose to face the RECOs herself rather than let the island keep fighting on her behalf?",
      "Write your own prediction of what might happen to Roz next — and how Brightbill might react when he returns to find her gone."),
  },
  projects: [
    P("poster", "Farewell", "Design a \"Missing\" or \"Farewell\" poster the island animals might put up for Roz."),
    P("comic", "The RECOs Arrive", "Show the RECOs' arrival and the island's attempt to protect Roz."),
    P("drama", "The Confrontation", "Act out the final confrontation between Roz and the RECOs, staying respectful to the book's tone."),
    P("journal", "Did She Make the Right Choice?", "Write your own opinion on whether Roz made the right choice at the end of the book, backed up with evidence."),
  ],
  quiz: [
    Q("What happens to Brightbill at the start of this week's chapters?", "He migrates away with the wild geese."),
    Q("True or False: Roz tries to stop Brightbill from leaving with the geese.", "False.", "tf"),
    Q("Who arrives on the island looking for Roz?", "The RECOs (robot retrieval/recovery units sent by her manufacturer)."),
    Q("Vocabulary: What does \"retrieve\" mean in this context?", "To find and bring back/reclaim."),
    Q("Why have the RECOs been sent to the island?", "To find and take Roz back/deal with her as a \"malfunctioning\" or unaccounted-for unit."),
    Q("Why might Roz's creators view her differently from how the island views her?", "Open — creators see her as property/a malfunction; the island sees her as family/a member of their community."),
    Q("True or False: The island animals do nothing to help Roz when the RECOs arrive.", "False — they try to protect/hide her.", "tf"),
    Q("Name one thing the island community does to try to protect Roz.", "Open, text-based."),
    Q("What does the community's protection of Roz prove about their relationship with her now?", "Open-ended — deep loyalty/love, she is truly one of them."),
    Q("What choice does Roz ultimately make regarding the RECOs?", "Open — she faces them/gives herself up to protect the island, per your edition's ending."),
    Q("Why might Roz choose to face the RECOs herself, rather than let the island keep fighting for her?", "Open — to protect the animals she loves from harm."),
    Q("Do you agree with Roz's final choice? Explain your opinion with evidence.", "Open-ended, opinion-based, must reference the text."),
    Q("Vocabulary: What does \"sacrifice\" mean?", "Giving up something important for the sake of someone/something else."),
    Q("Whole-book review: What is the very first major event that starts Roz's story?", "The storm/shipwreck that leaves her on the island."),
    Q("Whole-book review: Who is the gosling Roz raises, and how did he come into her care?", "Brightbill; the sole survivor of a nest Roz accidentally destroyed."),
    Q("Whole-book review: Name one moment where the island community's feelings toward Roz clearly changed for the better.", "Open — e.g. helping her during the winter storm."),
    Q("Whole-book review: What theme do you think this book explores most strongly?", "Open-ended — e.g. found family, belonging, adaptability, kindness, sacrifice."),
    Q("Whole-book review: How does Roz change from the beginning of the book to the end?", "Open-ended — from feared outsider/machine to beloved, self-sacrificing member of a family/community."),
    Q("Predict: What do you think Brightbill will do when he returns and finds Roz gone?", "Open-ended, text-supported prediction."),
    Q("What is the one big idea from this whole book you will remember most?", "Open-ended, personal response."),
  ],
},
];

const WEEK10 = {
  title: "Final Project & Celebration",
  options: [
    { title: "Found Family Campaign", desc: "Create a campaign (posters, slogans, a short speech) celebrating the idea that family is built through care, not sameness, using Roz and Brightbill's story as the model." },
    { title: "Extended Drama/Performance", desc: "Imagine Brightbill's journey to find Roz after the book ends, or dramatise a moment from the RECOs' point of view, told with empathy rather than as simple \"villains.\"" },
    { title: "Character Case File — Roz", desc: "An in-depth profile (poster + written report + panels) tracking Roz's journey and change across the whole book, with evidence from every part of the story she appears in." },
    { title: "\"How I Adapted\" Class Anthology", desc: "Each student contributes one illustrated page titled \"How I Adapted,\" a real-life story of a time they adapted to change, echoing Roz's own journey." },
  ],
  lessons: [
    { day: "Monday", title: "Plan", desc: "Choose project, plan/storyboard, gather resources, assign group roles." },
    { day: "Tuesday", title: "Produce", desc: "Main production time." },
    { day: "Wednesday", title: "Polish", desc: "Finishing touches, rehearsal/polish, prepare for presenting." },
  ],
  thursday: "Presentation / Gallery Walk Day — students present or display their final projects. Peer feedback via \"Glow & Grow\" sticky notes (one thing that shone, one thing to consider next time).",
  friday: "Celebration & Whole-Unit Reflection — no quiz this week. Whole-class reflection circle: share the one big idea students will carry forward from this book. Certificates presented. Optional: share favourite moments from the term.",
  rubric: [
    { criteria: "Understanding of the text", code: "R1",
      na: "Retells a few basic plot events.",
      wt: "Explains some of Roz's motivations or relationships, with limited evidence.",
      a: "Explains a theme (belonging, sacrifice, adapting) and supports it with clear evidence from the book.",
      example: "A Character Case File showing Roz changing from 'the monster' to Brightbill's mother, with an event from the beginning, middle and end of the book." },
    { criteria: "Communication of ideas", code: "R4 · R5",
      na: "Ideas are unclear or unfinished.",
      wt: "Ideas are mostly clear but not always organised for the audience.",
      a: "Ideas are clear, organised and suit the audience and purpose.",
      example: "A Found Family campaign poster with a catchy slogan, three persuasive reasons and a picture that matches the message." },
    { criteria: "Creativity & effort", code: "R6",
      na: "Minimal effort or detail; work is incomplete.",
      wt: "Some effort shown; parts are rushed or unfinished.",
      a: "Finished work showing care, original ideas and improvements made after feedback.",
      example: "A drama that adds a new scene from the RECOs' point of view, rehearsed and improved after a Glow & Grow from another group." },
    { criteria: "Collaboration (if group)", code: "R7 · R9",
      na: "Limited teamwork; relies on others to do the work.",
      wt: "Works with others when prompted; does their own part.",
      a: "Shares the work fairly, listens to others and helps the group succeed.",
      example: "Each member has a clear role, the group checks in with each other, and everyone presents a part." },
  ],
};

const DAY_ORDER = ["mon", "tue", "wed", "thu", "fri"];
const DAY_LABELS = { mon: "Monday — Teacher Read", tue: "Tuesday — Group Read", wed: "Wednesday — Teacher Read", thu: "Thursday — Group Read", fri: "Friday — Quiz" };
const DAY_MODE = { mon: "teacher", tue: "group", wed: "teacher", thu: "group", fri: "quiz" };
